spring.application.name=SpringJDBCCourse
spring.datasource.url= jdbc:postgresql://localhost:5432/SpringBootDemo
spring.datasource.username=postgres
spring.datasource.password=3591
spring.datasource.initialization-mode=always
spring.datasource.continue-on-error=true
#remove after development
#spring.sql.init.mode=always
